package com.gaozhaoyang.agent.casework;

public enum CaseStage {
    ANALYZING_REQUIREMENT,
    WAITING_FOR_CLARIFICATION,
    RESEARCHING_EVIDENCE,
    EVIDENCE_INSUFFICIENT,
    GENERATING_SOLUTION,
    WAITING_FOR_IMPLEMENTER_REVIEW,
    REVISION_REQUESTED,
    PUBLISHED,
    CANCELED,
    FAILED
}
